spring:
#  redis集群配置
  redis:
    timeout: 6000ms
    password: #scott@163
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

#  RabbitMQ单机配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual #设置确认模式手工确认
        concurrency: 10 #消费者最小数量
        max-concurrency: 20 # 消费者最大数量
        prefetch: 50
        retry:
          enabled: true # 是否支持重试